import { Clock3, Eye, LogOut, MapPin, UserRound } from 'lucide-react'
import type { LibrarySession } from '../../types'
import { Badge } from '../ui/Badge'
import { Button } from '../ui/Button'
import { formatDateTime, formatDuration } from './sessionUtils'

interface SessionTableProps { sessions: LibrarySession[]; onView: (session: LibrarySession) => void; onMarkExit: (session: LibrarySession) => void }

export function SessionTable({ sessions, onView, onMarkExit }: SessionTableProps) {
	return <div className="hidden overflow-x-auto md:block"><table className="w-full border-collapse text-left"><thead><tr className="border-b border-slate-100 bg-slate-50/75 text-xs font-semibold uppercase tracking-wider text-slate-500"><th className="px-6 py-3">Student</th><th className="px-4 py-3">Student ID</th><th className="px-4 py-3">Seat</th><th className="px-4 py-3">Section</th><th className="px-4 py-3">Entry Time</th><th className="px-4 py-3">Exit Time</th><th className="px-4 py-3">Duration</th><th className="px-4 py-3">Status</th><th className="px-6 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100 text-sm">{sessions.map((session) => <tr key={session.id} className="transition-colors hover:bg-slate-50/60"><td className="px-6 py-3.5"><div className="flex items-center gap-2"><UserRound className="h-4 w-4 text-slate-400" /><div><p className="font-semibold text-slate-900">{session.studentName}</p><p className="mt-0.5 text-xs text-slate-400">{session.department}</p></div></div></td><td className="px-4 py-3.5 font-mono text-xs text-slate-600">{session.studentId}</td><td className="px-4 py-3.5"><span className="flex items-center gap-1 text-xs font-medium text-slate-700"><MapPin className="h-3.5 w-3.5 text-slate-400" />{session.seatNumber}</span></td><td className="px-4 py-3.5 text-xs text-slate-600">Section {session.section}</td><td className="px-4 py-3.5 text-xs text-slate-600"><span className="flex items-center gap-1"><Clock3 className="h-3.5 w-3.5 text-slate-400" />{formatDateTime(session.entryTime)}</span></td><td className="px-4 py-3.5 text-xs text-slate-600">{session.exitTime ? formatDateTime(session.exitTime) : '—'}</td><td className="px-4 py-3.5 font-mono text-xs font-semibold text-slate-700">{formatDuration(session)}</td><td className="px-4 py-3.5"><Badge variant={session.status === 'active' ? 'success' : 'default'} dot>{session.status === 'active' ? 'Active' : 'Completed'}</Badge></td><td className="px-6 py-3.5 text-right"><div className="flex justify-end gap-1.5"><Button variant="ghost" size="sm" icon={<Eye className="h-3.5 w-3.5" />} onClick={() => onView(session)}>View</Button>{session.status === 'active' && <Button variant="outline" size="sm" icon={<LogOut className="h-3.5 w-3.5" />} onClick={() => onMarkExit(session)}>Mark Exit</Button>}</div></td></tr>)}</tbody></table></div>
}
