import type { Student } from '../../types'

export const INITIAL_MOCK_STUDENTS: Student[] = [
  {
    id: 'STU-2026-0142',
    qrToken: 'mock-qr-stu-2026-0142',
    fullName: 'Aarav Sharma',
    email: 'aarav.sharma@campus.edu',
    department: 'Computer Science',
    year: '3rd Year',
    division: 'Div A',
    status: 'inside',
    currentSeat: 'Desk A-14',
    joinedDate: 'Aug 2024',
    lastVisit: 'Today, 09:15 AM',
  },
  {
    id: 'STU-2026-0188',
    qrToken: 'mock-qr-stu-2026-0188',
    fullName: 'Elena Rostova',
    email: 'elena.rostova@campus.edu',
    department: 'Electrical Engineering',
    year: '2nd Year',
    division: 'Div B',
    status: 'inside',
    currentSeat: 'Desk B-02',
    joinedDate: 'Sep 2024',
    lastVisit: 'Today, 09:40 AM',
  },
  {
    id: 'STU-2026-0219',
    qrToken: 'mock-qr-stu-2026-0219',
    fullName: 'Marcus Chen',
    email: 'marcus.chen@campus.edu',
    department: 'Information Technology',
    year: '4th Year',
    division: 'Div A',
    status: 'inside',
    currentSeat: 'Desk C-08',
    joinedDate: 'Aug 2023',
    lastVisit: 'Today, 10:05 AM',
  },
  {
    id: 'STU-2026-0294',
    qrToken: 'mock-qr-stu-2026-0294',
    fullName: 'Priya Nair',
    email: 'priya.nair@campus.edu',
    department: 'Business Administration',
    year: '1st Year',
    division: 'Div C',
    status: 'inside',
    currentSeat: 'Desk A-22',
    joinedDate: 'Jan 2025',
    lastVisit: 'Today, 10:20 AM',
  },
  {
    id: 'STU-2026-0305',
    qrToken: 'mock-qr-stu-2026-0305',
    fullName: 'Liam O\'Connor',
    email: 'liam.oconnor@campus.edu',
    department: 'Mechanical Engineering',
    year: '3rd Year',
    division: 'Div B',
    status: 'inside',
    currentSeat: 'Desk B-15',
    joinedDate: 'Aug 2024',
    lastVisit: 'Today, 10:45 AM',
  },
  {
    id: 'STU-2026-0331',
    qrToken: 'mock-qr-stu-2026-0331',
    fullName: 'Sofia Alvarez',
    email: 'sofia.alvarez@campus.edu',
    department: 'Civil Engineering',
    year: '2nd Year',
    division: 'Div A',
    status: 'active',
    currentSeat: null,
    joinedDate: 'Sep 2024',
    lastVisit: 'Yesterday, 04:30 PM',
  },
  {
    id: 'STU-2026-0377',
    qrToken: 'mock-qr-stu-2026-0377',
    fullName: 'Devon Vance',
    email: 'devon.vance@campus.edu',
    department: 'Computer Science',
    year: '4th Year',
    division: 'Div A',
    status: 'active',
    currentSeat: null,
    joinedDate: 'Aug 2023',
    lastVisit: 'Yesterday, 02:15 PM',
  },
  {
    id: 'STU-2026-0412',
    qrToken: 'mock-qr-stu-2026-0412',
    fullName: 'Maya Patel',
    email: 'maya.patel@campus.edu',
    department: 'Electrical Engineering',
    year: '1st Year',
    division: 'Div C',
    status: 'active',
    currentSeat: null,
    joinedDate: 'Jan 2025',
    lastVisit: '3 days ago',
  },
  {
    id: 'STU-2026-0450',
    qrToken: 'mock-qr-stu-2026-0450',
    fullName: 'Julian Mercer',
    email: 'julian.mercer@campus.edu',
    department: 'Mechanical Engineering',
    year: '4th Year',
    division: 'Div A',
    status: 'active',
    currentSeat: null,
    joinedDate: 'Aug 2023',
    lastVisit: 'Sep 08, 2026',
  },
  {
    id: 'STU-2026-0489',
    qrToken: 'mock-qr-stu-2026-0489',
    fullName: 'Zainab Qureshi',
    email: 'zainab.qureshi@campus.edu',
    department: 'Information Technology',
    year: '2nd Year',
    division: 'Div B',
    status: 'active',
    currentSeat: null,
    joinedDate: 'Sep 2024',
    lastVisit: 'Sep 09, 2026',
  },
  {
    id: 'STU-2026-0521',
    qrToken: 'mock-qr-stu-2026-0521',
    fullName: 'Lucas Becker',
    email: 'lucas.becker@campus.edu',
    department: 'Civil Engineering',
    year: '3rd Year',
    division: 'Div C',
    status: 'inactive',
    currentSeat: null,
    joinedDate: 'Aug 2024',
    lastVisit: 'Last month',
  },
  {
    id: 'STU-2026-0564',
    qrToken: 'mock-qr-stu-2026-0564',
    fullName: 'Ananya Roy',
    email: 'ananya.roy@campus.edu',
    department: 'Business Administration',
    year: '4th Year',
    division: 'Div B',
    status: 'inactive',
    currentSeat: null,
    joinedDate: 'Aug 2023',
    lastVisit: 'Over 2 months ago',
  },
]

export const DEPARTMENTS = [
  'All Departments',
  'Computer Science',
  'Electrical Engineering',
  'Information Technology',
  'Mechanical Engineering',
  'Civil Engineering',
  'Business Administration',
] as const

export const ACADEMIC_YEARS = [
  'All Years',
  '1st Year',
  '2nd Year',
  '3rd Year',
  '4th Year',
] as const

export const DIVISIONS = ['Div A', 'Div B', 'Div C'] as const

export const STATUS_OPTIONS = [
  'All Statuses',
  'inside',
  'active',
  'inactive',
] as const
