import { useState } from 'react'
import { UserRound, X } from 'lucide-react'
import type { AdminProfile } from './mockSettings'
import { Button } from '../ui/Button'

interface EditProfileModalProps { profile: AdminProfile; onClose: () => void; onSave: (profile: AdminProfile) => void }

export function EditProfileModal({ profile, onClose, onSave }: EditProfileModalProps) {
  const [draft, setDraft] = useState(profile)
  const [error, setError] = useState('')
  const save = () => { if (!draft.name.trim()) { setError('Name is required.'); return } if (!/^\S+@\S+\.\S+$/.test(draft.email)) { setError('Enter a valid email address.'); return } onSave({ ...draft, name: draft.name.trim(), email: draft.email.trim() }) }
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><button type="button" className="absolute inset-0 bg-slate-900/40 backdrop-blur-2xs" onClick={onClose} aria-label="Close profile editor" /><div role="dialog" aria-modal="true" aria-labelledby="edit-profile-title" className="relative w-full max-w-md overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl"><div className="flex items-center justify-between border-b border-slate-100 bg-slate-50/60 p-5"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600"><UserRound className="h-4 w-4" /></div><div><h2 id="edit-profile-title" className="font-semibold text-slate-900">Edit Profile</h2><p className="text-xs text-slate-500">Update local administrator details.</p></div></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700" aria-label="Close profile editor"><X className="h-5 w-5" /></button></div><div className="space-y-4 p-5">{error && <p className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-xs text-rose-700">{error}</p>}<Field id="profile-name" label="Name" value={draft.name} onChange={(name) => setDraft({ ...draft, name })} /><Field id="profile-email" label="Email" value={draft.email} onChange={(email) => setDraft({ ...draft, email })} type="email" /><Field id="profile-role" label="Role" value={draft.role} onChange={(role) => setDraft({ ...draft, role })} /><Field id="profile-library" label="Library" value={draft.library} onChange={(library) => setDraft({ ...draft, library })} /></div><div className="flex justify-end gap-2 border-t border-slate-100 p-5"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="button" variant="primary" onClick={save}>Save Profile</Button></div></div></div>
}

function Field({ id, label, value, type = 'text', onChange }: { id: string; label: string; value: string; type?: string; onChange: (value: string) => void }) { return <div><label htmlFor={id} className="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-slate-700">{label}</label><input id={id} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 focus:border-indigo-500 focus:bg-white focus:outline-hidden focus:ring-2 focus:ring-indigo-500/20" /></div> }
