import type { LibrarySettings } from './mockSettings'

interface LibraryInformationProps { value: LibrarySettings; errors: Record<string, string>; onChange: (field: keyof LibrarySettings, value: string) => void }

export function LibraryInformation({ value, errors, onChange }: LibraryInformationProps) {
  return <div className="space-y-5"><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><Field id="library-name" label="Library Name" value={value.libraryName} error={errors.libraryName} onChange={(next) => onChange('libraryName', next)} required /><Field id="library-code" label="Library Code" value={value.libraryCode} error={errors.libraryCode} onChange={(next) => onChange('libraryCode', next)} required /><Field id="library-location" label="Location" value={value.location} onChange={(next) => onChange('location', next)} /><Field id="contact-email" label="Contact Email" type="email" value={value.contactEmail} error={errors.contactEmail} onChange={(next) => onChange('contactEmail', next)} /></div><div className="grid grid-cols-1 gap-4 border-t border-slate-100 pt-4 sm:grid-cols-2"><Field id="opening-time" label="Opening Time" type="time" value={value.openingTime} error={errors.openingTime} onChange={(next) => onChange('openingTime', next)} required /><Field id="closing-time" label="Closing Time" type="time" value={value.closingTime} error={errors.closingTime} onChange={(next) => onChange('closingTime', next)} required /></div></div>
}

function Field({ id, label, value, type = 'text', error, required, onChange }: { id: string; label: string; value: string; type?: string; error?: string; required?: boolean; onChange: (value: string) => void }) { return <div><label htmlFor={id} className="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-slate-700">{label} {required && <span className="text-rose-500">*</span>}</label><input id={id} type={type} value={value} onChange={(event) => onChange(event.target.value)} className={`w-full rounded-lg border bg-slate-50 px-3 py-2 text-sm text-slate-900 focus:bg-white focus:outline-hidden focus:ring-2 ${error ? 'border-rose-300 focus:border-rose-500 focus:ring-rose-500/20' : 'border-slate-200 focus:border-indigo-500 focus:ring-indigo-500/20'}`} />{error && <p className="mt-1 text-xs text-rose-600">{error}</p>}</div> }
