import { Armchair, CheckCircle2, Construction, Users } from 'lucide-react'
import type { ReactNode } from 'react'
import type { LibrarySettings } from './mockSettings'

interface SeatConfigurationProps { value: LibrarySettings; counts: { total: number; available: number; occupied: number; maintenance: number }; onChange: (field: keyof LibrarySettings, value: string | Record<'A' | 'B' | 'C' | 'D', boolean>) => void }

export function SeatConfiguration({ value, counts, onChange }: SeatConfigurationProps) {
  const sections = Object.keys(value.enabledSections) as Array<'A' | 'B' | 'C' | 'D'>
  const toggleSection = (section: 'A' | 'B' | 'C' | 'D') => onChange('enabledSections', { ...value.enabledSections, [section]: !value.enabledSections[section] })
  return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Total seats" value={counts.total} icon={<Armchair className="h-4 w-4 text-indigo-600" />} /><Metric label="Available" value={counts.available} icon={<CheckCircle2 className="h-4 w-4 text-emerald-600" />} /><Metric label="Occupied" value={counts.occupied} icon={<Users className="h-4 w-4 text-amber-600" />} /><Metric label="Maintenance" value={counts.maintenance} icon={<Construction className="h-4 w-4 text-rose-600" />} /></div><div className="border-t border-slate-100 pt-4"><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-700">Enabled sections</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{sections.map((section) => <button key={section} type="button" aria-pressed={value.enabledSections[section]} onClick={() => toggleSection(section)} className={`rounded-lg border px-3 py-2 text-sm font-semibold transition-colors ${value.enabledSections[section] ? 'border-indigo-200 bg-indigo-50 text-indigo-700' : 'border-slate-200 bg-slate-50 text-slate-400'}`}>Section {section}<span className="mt-0.5 block text-[10px] font-normal">{value.enabledSections[section] ? 'Enabled' : 'Disabled'}</span></button>)}</div></div><div className="grid grid-cols-1 gap-4 border-t border-slate-100 pt-4 sm:grid-cols-2"><label className="text-xs font-semibold uppercase tracking-wider text-slate-700">Default section<select value={value.defaultSection} onChange={(event) => onChange('defaultSection', event.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm font-normal normal-case tracking-normal text-slate-900 focus:border-indigo-500 focus:outline-hidden focus:ring-2 focus:ring-indigo-500/20">{sections.map((section) => <option key={section} value={section}>Section {section}</option>)}</select></label><label className="text-xs font-semibold uppercase tracking-wider text-slate-700">Seat naming preference<select value={value.seatNaming} onChange={(event) => onChange('seatNaming', event.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm font-normal normal-case tracking-normal text-slate-900 focus:border-indigo-500 focus:outline-hidden focus:ring-2 focus:ring-indigo-500/20"><option value="compact">Compact (A01)</option><option value="descriptive">Descriptive (Section A - 01)</option></select></label></div><p className="text-xs text-slate-400">These controls are local preferences for the mock interface and do not alter the shared seat map.</p></div>
}

function Metric({ label, value, icon }: { label: string; value: number; icon: ReactNode }) { return <div className="rounded-lg border border-slate-200/80 bg-slate-50/60 p-3"><p className="flex items-center gap-1.5 text-xs text-slate-500">{icon}{label}</p><p className="mt-1 text-xl font-bold text-slate-900">{value}</p></div> }
